- name: Create nginx config
  template:
    src: nginx.j2
    dest: '/etc/nginx/conf.d/{{site_name}}.conf'
  become: yes
- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes
