- name: Install Web Management service
  win_feature:
    name: Web-Mgmt-Service
- name: Enable remote access
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\WebManagement\Server
    name: EnableRemoteManagement
    data: 1
    type: dword
- name: Change service startup type
  win_service:
    name: WMSVC
    start_mode: auto
- name: Replace WMSVC SSL certificate
  win_shell: |
    $InformationPreference = 'Continue'

    # Replace WMSvc-HOST with HOST certificate. It should be generated already during WinRM configuration.
    Import-Module WebAdministration
    $wmsvcBindingPath = 'IIS:\SslBindings\0.0.0.0!8172'
    $winrmCertificate = (Get-Item IIS:\SslBindings\0.0.0.0!5986).Thumbprint
    $webManagementCertificate = (Get-Item $wmsvcBindingPath).Thumbprint

    if ($winrmCertificate -ne $webManagementCertificate)
    {
        Get-Item -Path "Cert:\LocalMachine\My\$winrmCertificate" | Set-Item $wmsvcBindingPath
        Write-Information 'Changed certificate for WMSVC binding.'
    }
    else
    {
        Write-Information 'Certificate for WMSVC binding is not changed.'
    }
  register: wmsvc_result
  failed_when: wmsvc_result.stderr
