- hosts: buildservers

  roles:
    - ocha.dotnet-core
    - brentwg.powershell
    - geerlingguy.jenkins

  vars:
    dotnet_package: dotnet-sdk-2.1
    ansible_become: true
    jenkins_plugins:
      - workflow-aggregator
      - ssh-agent
      - git
    jenkins_plugin_timeout: 300

  tasks:
    - name: Open 8080 port
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
      become: yes
      when: ansible_os_family == 'RedHat'
    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
      become: yes
      when: ansible_os_family == 'RedHat'
    - name: Install Git
      yum:
        name: git
        state: present
      become: yes
      when: ansible_os_family == 'RedHat'
    - name: Clone psake repository
      git:
        repo: 'https://github.com/psake/psake'
        dest: /opt/psake
    - name: Create psake wrapper
      copy:
        content: |
          #!/usr/bin/env sh
          pwsh -Command "& /opt/psake/src/psake.ps1 $@; if (\$psake.build_success -eq \$false) { exit 1 } else { exit 0 }"
        dest: /usr/bin/psake
        mode: 0755

  pre_tasks:
    - name: Enable Universe repository
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
      become: yes
      when: ansible_os_family == 'Debian'
    - name: Choose Java version (Debian)
      set_fact:
        java_packages:
          - openjdk-8-jre
      when: ansible_os_family == 'Debian'
    - name: Choose Java version (RedHat)
      set_fact:
        java_packages:
          - java-1.8.0-openjdk
      when: ansible_os_family == 'RedHat'
